# Generated by Django 2.1.7 on 2019-03-22 20:27

import PredictiveAcceptance.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupValues',
            fields=[
                ('lookup_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lookup_type', models.CharField(max_length=50, unique=True)),
                ('lookup_value', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'lookup_values',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictiveUsers',
            fields=[
                ('user_id', models.IntegerField(default=PredictiveAcceptance.models.userId, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('email_address', models.CharField(max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'predictive_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityNames',
            fields=[
                ('university_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=50, unique=True)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'university_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversitySampleData',
            fields=[
                ('sample_data', models.AutoField(primary_key=True, serialize=False)),
                ('grescore', models.IntegerField()),
                ('englishtest', models.IntegerField()),
                ('undergradcgpa', models.IntegerField()),
                ('workex_months', models.IntegerField()),
                ('research_skills', models.IntegerField()),
                ('acceptancepercentage', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'university_sample_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('user_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=20, unique=True)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfiles',
            fields=[
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='PredictiveAcceptance.PredictiveUsers')),
                ('firstname', models.CharField(max_length=30)),
                ('middlename', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(max_length=20)),
                ('grescore', models.IntegerField()),
                ('englishtest', models.IntegerField()),
                ('undergradcgpa', models.IntegerField()),
                ('workex_months', models.IntegerField()),
                ('research_skills', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'student_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversitySummaries',
            fields=[
                ('university_code', models.ForeignKey(db_column='university_code', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='PredictiveAcceptance.UniversityNames')),
                ('avg_grescore', models.IntegerField()),
                ('avg_ielts', models.IntegerField()),
                ('avg_toefl', models.IntegerField()),
                ('avg_undergradcgpa', models.IntegerField()),
                ('avg_workex_months', models.IntegerField()),
                ('avg_research_skills', models.IntegerField()),
                ('avg_acceptancepercentage', models.IntegerField()),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'university_summaries',
                'managed': False,
            },
        ),
    ]
